version: '3.7'
services:
  appling:
    container_name: appling
    build: .
    ports:
      - 8000:8000
    environment:
      - server.profile=prod
      - TZ=Asia/Seoul
      - db.url=jdbc:mysql://master/appling
      - db.username=juno
      - db.password=password
      - s3.id=${S3_ID}
      - s3.key=${S3_KEY}
      - kakao.id=${KAKAO_ID}
      - kakao.url=${KAKAO_URL}
      - google.key=${GOOGLE_KEY}
    volumes:
      - /log:/log
networks:
  default:
    external:
      name: normal

