version: '3.7'
services:
  appling:
    container_name: ${CONTAINER_NAME}
    build: .
    ports:
      - ${API_PORT}:8000
    environment:
      - server.profile=${API_PROFILE}
      - TZ=Asia/Seoul
      - db.url=${MYSQL_URL}
      - db.username=juno
      - db.password=password
      - s3.id=${S3_ID}
      - s3.key=${S3_KEY}
      - kakao.id=${KAKAO_ID}
      - kakao.url=${KAKAO_URL}
      - google.key=${GOOGLE_KEY}
    volumes:
      - /log:/log
networks:
  default:
    external:
      name: normal

